# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install mdm-cli -g'
    feedsToUse: 'select'
    vstsFeed: '$(draft-feed)'

- script: |
    mdm-cli typescript https://alejandro.iglesias:$(script-token)@github.com/trifenix/mdm-auto-npm.git -b develop -t model -u alejandro.iglesias -e alejandro.iglesias@trifenix.io
  displayName: "Ejecutando comando que actualiza github"

    