# termine, parte 1.

trigger:
    branches:
      include:        
        - master  
pool:
  vmImage: "windows-latest"

variables: 
  BuildConfiguration: 'release'
  # nombre del archivo csproj
  name-project: "trifenix.connect.mdm"

  
# github ejecuta este build, para validar y ejecutar,
# es decir, dos veces
# esta instrucción asigna que no se ejecute en el pull request (para validar).
# sino, que solo se ejecute al modificar la rama.
pr: none
  
steps:

  
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'AGROFENIX-mdm'
      scannerMode: 'MSBuild'
      projectKey: 'AGROFENIX-mdm'
      projectName: 'AGROFENIX-mdm'
  
  
  # toma todos los proyectos que existan además de quien tiene el nuget.
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: '$(default-feed)'      
      versioningScheme: byBuildNumber

  - task: CmdLine@2
    inputs:
      script: |
        dotnet tool install trifenix.versions.console -g
        FOR /F "tokens=* USEBACKQ" %%F IN (`trifenix-versions update https://github.com/trifenix/versions.git --token $(script-token) --user trifenix --email devops@trifenix.io --branch master --name trifenix.connect.mdm --ktype nuget --build $(Build.BuildId)`) DO (
          SET var=%%F
        )
        ECHO %var%
        dotnet pack $(name-project).csproj --no-build --configuration $(BuildConfiguration) /p:Version=%var% --output nupkgs
    displayName: "Generando paquete con la versión"
  - task: SonarQubeAnalyze@4
  - task: SonarQubePublish@4
    inputs:
      pollingTimeoutSec: '300'
  # publica paquete para publicar.
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: drop
      publishLocation: 'container'
    displayName: "publish nuget"